apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
  namespace: app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-app
        image: ghcr.io/marcelhimmelreichcm/cluster-vue-app/vue-app:latest
        ports:
        - containerPort: 80
