apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
  namespace: vue-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-app
        image: yourdockerhubusername/vue-app:latest
        ports:
        - containerPort: 80
