apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vue-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/marcelhimmelreichcm/cluster-vue-app.git'
    targetRevision: HEAD
    path: deploy
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
